api_platform:
    mapping:
        paths:
          - '%kernel.project_dir%/src/Entity'
          - '%kernel.project_dir%/src/Dto'

    http_cache:
        etag: true
        max_age: 3600
        shared_max_age: 3600
        vary: ['Accept']
        public: true
        invalidation:
          enabled: false
          varnish_urls: []
