doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        options:
            !php/const:PDO::MYSQL_ATTR_SSL_CA: '%env(resolve:MYSQL_CA_CERT)%'
            !php/const:PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: '%env(resolve:MYSQL_USE_SSL)%'
        types:
          chgkdb_question_type:
            class: 'App\Entity\QuestionTypeType'
          chgkdb_text_id:
            class: 'App\Entity\TextIdType'

        mapping_types:
            enum: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        dql:
            string_functions:
                field: DoctrineExtensions\Query\Mysql\Field
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
