security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
              users:
                  db.chgk.info:
                      password: "%env(resolve:ACCESS_PASSWORD)%"
                      roles: "ROLE_EDITOR"
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        unsecured:
            pattern: ^/(questions/validate|validator)
            anonymous: true
        secured:
            pattern: ^/
            methods: [POST, PUT, PATCH, DELETE]
            http_basic: true
        main:
            anonymous: true

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
