security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory:
            memory:
              users:
                  db.chgk.info:
                      password: "%env(resolve:ACCESS_PASSWORD)%"
                      roles: "ROLE_EDITOR"
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        unsecured:
            pattern: ^/(questions/validate|validator)
            anonymous: true
        secured:
            pattern: ^/
            methods: [POST, PUT, PATCH, DELETE]
            http_basic: true
        main:
            anonymous: lazy
            provider: in_memory
